version: '3'
services:
    app:
        container_name: 'aws-app'
        build:
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8081:8081'
        volumes:
            - '.:/usr/src/app'
        networks:
            - aws_app_localstack_network
        depends_on:
            - localstack
    localstack:
        container_name: 'aws-app-localstack'
        image: localstack/localstack
        ports:
            - '127.0.0.1:4566:4566'             # LocalStack Gateway
            - '127.0.0.1:3510-3559:4510-4559'   # external services port range
        environment:
            - DEBUG=${DEBUG-}
            - PERSISTENCE=${PERSISTENCE-}
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
            - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
            - DOCKER_HOST=unix:///var/run/docker.sock
            - SERVICES=s3 # comma-separated list of services
        volumes:
            - 'volume-localstack:/var/lib/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - aws_app_localstack_network
networks:
    aws_app_localstack_network:
        driver: bridge
volumes:
    volume-localstack:
        driver: local